name: Sync

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository == 'yanglbme/geetest-crack'
    steps:
    - name: Sync to gitee.com
      uses: wearerequired/git-mirror-action@master
      env:
          SSH_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
      with:
          source-repo: git@github.com:yanglbme/geetest-crack.git
          destination-repo: git@gitee.com:yanglbme/geetest-crack.git
          
